import type { CourseGalaxyResponse } from '@/types'

// Galaxia demo con el mismo contrato que GET /courses/galaxy. Cubre los casos
// borde de SPEC 02: curso en 2 galaxias (nextjs-app-router), curso inactivo
// (vue-composition-api), curso sin coordenadas (docker-guia-practica) y
// prerequisito con slug inexistente (angular-pro → rxjs-desde-cero).
export const galaxyMock: CourseGalaxyResponse = {
  galaxies: [
    { key: 'frontend', name: 'Frontend & UI', color: '#3B82F6', center: { x: 54, y: 6, z: 18 } },
    { key: 'backend', name: 'Backend & APIs', color: '#10B981', center: { x: -48, y: -3, z: 24 } },
    { key: 'mobile', name: 'Mobile', color: '#F59E0B', center: { x: 6, y: 9, z: -54 } },
    { key: 'devops', name: 'DevOps & Cloud', color: '#A855F7', center: { x: -12, y: -12, z: 60 } },
  ],
  courses: [
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000001',
      slug: 'typescript-guia-completa',
      title: 'TypeScript: Guía completa',
      category: 'frontend',
      level: 'beginner',
      tags: ['typescript', 'javascript'],
      isActive: true,
      galaxies: ['frontend'],
      galaxyColor: '#3B82F6',
      positionX: 42.6, positionY: 4.2, positionZ: 27.3,
      prerequisites: [],
      related: ['angular-de-cero-a-experto', 'react-de-cero-a-experto'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000002',
      slug: 'angular-de-cero-a-experto',
      title: 'Angular: De cero a experto',
      category: 'frontend',
      level: 'beginner',
      tags: ['angular', 'typescript'],
      isActive: true,
      galaxies: ['frontend'],
      galaxyColor: '#3B82F6',
      positionX: 61.5, positionY: 9.6, positionZ: 31.2,
      prerequisites: ['typescript-guia-completa'],
      related: ['angular-pro'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000003',
      slug: 'angular-pro',
      title: 'Angular Pro: Lleva tus bases al siguiente nivel',
      category: 'frontend',
      level: 'intermediate',
      tags: ['angular', 'typescript', 'rxjs'],
      isActive: true,
      galaxies: ['frontend'],
      galaxyColor: '#3B82F6',
      positionX: 71.4, positionY: 3.3, positionZ: 12.6,
      prerequisites: ['angular-de-cero-a-experto', 'typescript-guia-completa', 'rxjs-desde-cero'],
      related: ['nestjs-api-rest'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000004',
      slug: 'react-de-cero-a-experto',
      title: 'React: De cero a experto',
      category: 'frontend',
      level: 'beginner',
      tags: ['react', 'javascript', 'hooks'],
      isActive: true,
      galaxies: ['frontend'],
      galaxyColor: '#3B82F6',
      positionX: 46.8, positionY: 11.4, positionZ: 5.7,
      prerequisites: [],
      related: ['nextjs-app-router', 'react-native-expo'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000005',
      slug: 'nextjs-app-router',
      title: 'Next.js: El framework de React para producción',
      category: 'frontend',
      level: 'advanced',
      tags: ['nextjs', 'react', 'typescript', 'ssr'],
      isActive: true,
      galaxies: ['frontend', 'backend'],
      galaxyColor: '#3B82F6',
      positionX: 4.5, positionY: 3, positionZ: 22.5,
      prerequisites: ['react-de-cero-a-experto', 'typescript-guia-completa'],
      related: ['nestjs-api-rest'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000006',
      slug: 'vue-composition-api',
      title: 'Vue.js: Composition API',
      category: 'frontend',
      level: 'intermediate',
      tags: ['vue', 'javascript'],
      isActive: false,
      galaxies: ['frontend'],
      galaxyColor: '#3B82F6',
      positionX: 64.2, positionY: 0.6, positionZ: 3.9,
      prerequisites: ['typescript-guia-completa'],
      related: [],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000007',
      slug: 'node-de-cero-a-experto',
      title: 'Node: De cero a experto',
      category: 'backend',
      level: 'beginner',
      tags: ['node', 'javascript', 'express'],
      isActive: true,
      galaxies: ['backend'],
      galaxyColor: '#10B981',
      positionX: -39.3, positionY: -1.2, positionZ: 33.6,
      prerequisites: [],
      related: ['nestjs-api-rest'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000008',
      slug: 'nestjs-api-rest',
      title: 'NestJS: Desarrollo backend escalable con Node',
      category: 'backend',
      level: 'intermediate',
      tags: ['nestjs', 'node', 'typescript'],
      isActive: true,
      galaxies: ['backend'],
      galaxyColor: '#10B981',
      positionX: -56.1, positionY: 2.7, positionZ: 16.8,
      prerequisites: ['node-de-cero-a-experto', 'typescript-guia-completa'],
      related: ['nestjs-microservicios'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000009',
      slug: 'nestjs-microservicios',
      title: 'NestJS + Microservicios',
      category: 'backend',
      level: 'advanced',
      tags: ['nestjs', 'microservicios', 'nats', 'docker'],
      isActive: true,
      galaxies: ['backend'],
      galaxyColor: '#10B981',
      positionX: -63.9, positionY: -7.8, positionZ: 29.4,
      prerequisites: ['nestjs-api-rest', 'docker-guia-practica'],
      related: ['kubernetes-despliegues'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000010',
      slug: 'react-native-expo',
      title: 'React Native: Aplicaciones móviles con Expo',
      category: 'mobile',
      level: 'intermediate',
      tags: ['react-native', 'expo', 'typescript'],
      isActive: true,
      galaxies: ['mobile'],
      galaxyColor: '#F59E0B',
      positionX: 14.4, positionY: 12.3, positionZ: -45.9,
      prerequisites: ['react-de-cero-a-experto'],
      related: ['flutter-movil'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000011',
      slug: 'flutter-movil',
      title: 'Flutter: Tu guía completa de desarrollo iOS y Android',
      category: 'mobile',
      level: 'advanced',
      tags: ['flutter', 'dart'],
      isActive: true,
      galaxies: ['mobile'],
      galaxyColor: '#F59E0B',
      positionX: -3.6, positionY: 6.9, positionZ: -64.2,
      prerequisites: [],
      related: ['react-native-expo'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000012',
      slug: 'docker-guia-practica',
      title: 'Docker: Guía práctica de uso para desarrolladores',
      category: 'devops',
      level: 'beginner',
      tags: ['docker', 'contenedores'],
      isActive: true,
      galaxies: ['devops'],
      galaxyColor: '#A855F7',
      positionX: null, positionY: null, positionZ: null,
      prerequisites: [],
      related: ['kubernetes-despliegues'],
    },
    {
      id: '0b6f1a52-1c1e-4d0a-9a51-000000000013',
      slug: 'kubernetes-despliegues',
      title: 'Kubernetes: Despliegues en la nube',
      category: 'devops',
      level: 'advanced',
      tags: ['kubernetes', 'docker', 'cloud'],
      isActive: true,
      galaxies: ['devops'],
      galaxyColor: '#A855F7',
      positionX: -19.2, positionY: -15.6, positionZ: 69.3,
      prerequisites: ['docker-guia-practica'],
      related: ['nestjs-microservicios'],
    },
  ],
}
