import { Link } from 'react-router-dom'
import { useStarMap } from '@/hooks/useStarMap'

export default function LandingPage(): JSX.Element {
  const { canvasRef } = useStarMap({ count: 1000, background: true })
  return <main className="landing-screen"><canvas ref={canvasRef} className="starfield-canvas" aria-hidden="true" /><div className="landing-stars" /><div className="shooting-star shooting-star-one" /><div className="shooting-star shooting-star-two" /><svg className="background-constellation" viewBox="0 0 700 360" aria-hidden="true"><path d="M70 245 L190 120 L330 205 L470 80 L625 160" /><path d="M190 120 L250 300 L330 205" /></svg><header className="landing-nav"><img src="/assets/logo-devtalles.png" alt="DevTalles" /><nav><a href="#universe">Universo</a><a href="#constellations">Constelaciones</a><a href="#log">Bitácora</a></nav></header><section className="landing-hero"><div className="landing-copy"><span className="edition-pill">● Expedición 2026 · Abierta</span><h1 translate="no"><span className="mockup-title">CODE QUEST</span><b>2026</b></h1><p>El conocimiento es un universo. Cada curso es una estrella y<br className="desktop-only" /> tu ruta es la constelación que las une.</p><Link className="discord-btn" to="/login"><strong>●</strong> Iniciar sesión</Link><small className="explorers">8.400 exploradores<br />en ruta</small></div><div className="devi-frame"><div className="devi-orbit" /><img src="/assets/devi-hello.png" alt="Devi saludando" /></div></section><section className="feature-grid"><Feature number="01 · Diagnóstico" title="Cuestionario de 4 pasos" text="Intereses, nivel y ritmo semanal definen tu punto de partida." /><Feature number="02 · Mapa" title="Ruta visual por nodos" text="Cada nodo es un curso con prerrequisitos y estado en tiempo real." /><Feature number="03 · Progreso" title="Racha y métricas" text="Horas acumuladas, cursos cerrados y constancia día por día." /></section></main>
}

function Feature({ number, title, text }: { number: string; title: string; text: string }): JSX.Element { return <article className="feature-card"><b>{number}</b><h2 style={{ textTransform: 'none' }}>{title}</h2><p>{text}</p></article> }
