import { Link } from 'react-router-dom'
import Starfield from '@/components/galaxy/Starfield'
import './landing.css'
import './landing-animations.css'
import './landing-layout.css'
import './landing-motion.css'
import './shooting-star-exact.css'
import './constellation-exact.css'
import './star-density.css'
import './starfield-canvas.css'
import './typography-exact.css'
import './typography-mockup.css'
import './discord-button-exact.css'
import './feature-cards-exact.css'
import './hero-copy-exact.css'
import './cta-row-exact.css'
import './hero-grid-exact.css'
import './cta-nowrap.css'
import './cta-inline-fix.css'
import './cta-counter-offset.css'
import './devi-orbit.css'
import './landing-viewport.css'
const constellationStars: Array<[number, number]> = [[70, 245], [190, 120], [330, 205], [470, 80], [625, 160], [250, 300]]
export default function LandingPage(): JSX.Element { return <main className="landing-screen"><Starfield/><div className="landing-stars"/><div className="shooting-star shooting-star-one"/><div className="shooting-star shooting-star-two"/><svg className="background-constellation" viewBox="0 0 700 360" aria-hidden="true"><path d="M70 245 L190 120 L330 205 L470 80 L625 160"/><path d="M190 120 L250 300 L330 205"/>{constellationStars.map(([cx, cy]) => <circle cx={cx} cy={cy} r="4" key={`${cx}-${cy}`} />)}</svg><header className="landing-nav"><img src="/assets/logo-devtalles.png" alt="devtalles"/><nav><a href="#universe">UNIVERSO</a><a href="#constellations">CONSTELACIONES</a><a href="#log">BITÁCORA</a></nav></header><section className="landing-hero"><div className="landing-copy"><span className="edition-pill">● EXPEDICIÓN 2026 · ABIERTA</span><h1><span className="mockup-title">CODE QUEST</span><b>2026</b></h1><p>El conocimiento es un universo. Cada curso es una estrella y<br className="desktop-only"/> tu ruta es la constelación que las une.</p><Link className="discord-btn" to="/login"><strong>●</strong> INICIAR CON DISCORD</Link><small className="explorers">8.400 EXPLORADORES<br/>EN RUTA</small></div><div className="devi-frame"><div className="devi-orbit"/><img src="/assets/devi-hello.png" alt="Devi saludando"/></div></section><section className="feature-grid"><Feature number="01 · DIAGNÓSTICO" title="CUESTIONARIO DE 4 PASOS" text="Intereses, nivel y ritmo semanal definen tu punto de partida."/><Feature number="02 · MAPA" title="RUTA VISUAL POR NODOS" text="Cada nodo es un curso con prerequisitos y estado en tiempo real."/><Feature number="03 · PROGRESO" title="RACHA Y MÉTRICAS" text="Horas acumuladas, cursos cerrados y constancia día por día."/></section></main> }
function Feature({ number, title, text }: { number: string; title: string; text: string }): JSX.Element { return <article className="feature-card"><b>{number}</b><h2>{title}</h2><p>{text}</p></article> }
