import { Link, useParams } from 'react-router-dom'
import { useEffect } from 'react'
import { useState } from 'react'
import PageLayout from '@/components/layout/PageLayout'
import StarMap from '@/components/galaxy/StarMap'
import Badge from '@/components/ui/Badge'
import LoadingSpinner from '@/components/ui/LoadingSpinner'
import { usePathsStore } from '@/stores/paths.store'
import StarPanel from '@/components/galaxy/StarPanel'
import ViewToggle from '@/components/galaxy/ViewToggle'
export default function PathDetailPage(): JSX.Element { const { id = '' } = useParams<{ id: string }>(); const { currentPath, loading, fetchPath } = usePathsStore(); const [view, setView] = useState<'galaxy' | 'list'>('galaxy'); useEffect(() => { if (id) void fetchPath(id) }, [id, fetchPath]); const course = currentPath?.courses[0]; return <PageLayout>{loading ? <LoadingSpinner /> : !currentPath ? <><p className="text-brand-lime text-xs">// RUTAS DE APRENDIZAJE</p><h1 className="mt-4 text-4xl font-bold">RUTA NO DISPONIBLE</h1><p className="mt-4 text-slate-400">El backend todavía no expone rutas de aprendizaje.</p><Link className="mt-5 inline-block text-xs font-bold text-brand-lime" to="/dashboard">← VOLVER A RUTAS</Link></> : <><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs tracking-widest text-brand-lime">CONSTELACIÓN · {currentPath.title.toUpperCase()}</p><h1 className="mt-4 text-4xl font-bold">MAPA DE <span className="text-brand-lime">APRENDIZAJE</span></h1><p className="mt-3 text-xs text-slate-400">{currentPath.totalCourses} ESTRELLAS · HOVER PARA VER PREREQUISITOS</p></div><div className="flex items-center gap-5"><ViewToggle onChange={setView} /><Badge tone="success">RUTA ACTIVA</Badge></div></div>{view === 'galaxy' ? <div className="mt-8"><StarMap /></div> : <div className="mt-8 space-y-3">{currentPath.courses.map((item) => <div className="card" key={item.id}>{item.title}</div>)}</div>}<div className="mt-5"><StarPanel title={course?.title ?? 'Curso seleccionado'} /></div><Link className="mt-5 inline-block text-xs font-bold text-brand-lime" to="/dashboard">← VOLVER A RUTAS</Link></>}</PageLayout> }
